name: Linux baseline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  baseline:
    name: Linux baseline
    uses: ./.github/workflows/_linux-build.yml
    with:
      cache_namespace: pr
      package_release: false
